blog/urls.py
from django.urls import path
from blog.views import BlogCreateView, BlogDeleteView, BlogListView, BlogDetailView, BlogUpdateView
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('', BlogListView.as_view(), name='blog_list'),
    path('view/<slug:slug>', BlogDetailView.as_view(), name='blog_view'),
    path('edit/<slug:slug>', BlogUpdateView.as_view(), name='blog_edit'),
    path('delete/<slug:slug>', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blogpost')),
    path('users/', include('users.urls', namespace='user')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from pytils.translit import slugify


class BlogPost(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    slug = models.CharField(max_length=150, verbose_name='Slug')
    content = models.TextField(verbose_name='Содержимое')
    preview = models.ImageField(upload_to='blog_previews/', verbose_name='Превью (изображение)')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Признак публикации')
    views_count = models.IntegerField(default=0, verbose_name='Количество просмотров')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Запись блога'
        verbose_name_plural = 'Записи блога'

blog/views.py
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from pytils.translit import slugify

from blog.models import BlogPost
from django.urls import reverse_lazy, reverse

class BlogCreateView(CreateView):
    model = BlogPost
    fields = ['title', 'content', 'preview']
    success_url = reverse_lazy('blogpost:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post.slug = slugify(new_post.title)
            new_post.save()

        return super().form_valid(form)

class BlogListView(ListView):
    model = BlogPost

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = BlogPost

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object

class BlogDeleteView(DeleteView):
    model = BlogPost
    success_url = reverse_lazy('blogpost:blog_list')

class BlogUpdateView(UpdateView):
    model = BlogPost
    fields = ['title', 'content', 'preview']

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post.slug = slugify(new_post.title)
            new_post.save()
            self.kwargs['slug'] = new_post.slug

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blogpost:blog_view', args=[self.kwargs.get('slug')])

blog/templates/blog/blogpost_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container">
    <h1 class="display-4">Confirm Delete</h1>
    <p>Are you sure you want to delete the blog post with title: <strong>{{ object.title }}</strong>?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="/blog" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock content %}

blog/templates/blog/blogpost_detail.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container">
    <h1 class="display-4">{{ object.title }}</h1>
    <h1 class="display-4">{{ object.slug }}</h1>
    <img src="{{ object.preview.url }}" alt="{{ object.title }}" class="card-img-top">
    <p class="lead">{{ object.content }}</p>
    <p class="h3">Дата создания: {{ object.created_at }}</p>
    <p class="h3">Количество просмотров: {{ object.views_count }}</p>
</div>
{% endblock content %}

blog/templates/blog/blogpost_form.html
{% extends 'catalog/base.html' %} <!-- Предполагается, что у вас есть базовый шаблон base.html -->

{% block content %} <!-- Открываем блок для контента страницы -->
<div class="container">
    <h1 class="display-4">
        {% if object %}
                Edit Blog Post
            {% else %}
                Create Blog Post
            {% endif %}
    </h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="title">Title:</label>
            <input type="text" class="form-control" id="title" name="title" required>
        </div>
        <div class="form-group">
            <label for="content">Content:</label>
            <textarea class="form-control" id="content" name="content" required></textarea>
        </div>
        <div class="form-group">
            <label for="preview">Preview (Image):</label>
            <input type="file" class="form-control-file" id="preview" name="preview" required>
        </div>
        <button type="submit" class="btn btn-primary">
            {% if object %}
                Save
            {% else %}
                Create
            {% endif %}
        </button>
    </form>
</div>
{% endblock %} <!-- Закрываем блок для контента страницы -->

blog/templates/blog/blogpost_list.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12 mb-3">
            <h1 class="display-4">Blog Posts</h1>
            <a href="{% url 'blogpost:blog_create' %}" class="btn btn-primary float-right">Добавить</a>
        </div>
    </div>
    <div class="row">
        {% for post in object_list %}
        <div class="col-md-4 mb-4">
            <div class="card">
                <img src="{{ post.preview.url }}" alt="{{ post.title }}" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">{{ post.title }}</h5>
                    <p class="card-text">{{ post.content|truncatechars:100 }}</p>
                    <a href="{% url 'blogpost:blog_view' post.slug %}" class="btn btn-primary">View</a>
                    <a href="{% url 'blogpost:blog_edit' post.slug %}" class="btn btn-secondary">Edit</a>
                    <a href="{% url 'blogpost:blog_delete' post.slug %}" class="btn btn-danger">Delete</a>

                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}