blog/urls.py
from django.urls import path
from blog.views import BlogCreateView, BlogDeleteView, BlogListView, BlogDetailView, BlogUpdateView
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('', BlogListView.as_view(), name='blog_list'),
    path('view/<slug:slug>', BlogDetailView.as_view(), name='blog_view'),
    path('edit/<slug:slug>', BlogUpdateView.as_view(), name='blog_edit'),
    path('delete/<slug:slug>', BlogDeleteView.as_view(), name='blog_delete'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import ProductListView, ProductCreateView, ProductDetailView, ProductDeleteView, ProductUpdateView, \
    CategoryListView

app_name = CatalogConfig.name

urlpatterns = [
    # path('contacts/', contacts),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('', ProductListView.as_view(), name='product_list'),
    path('view/<int:pk>', cache_page(60)(ProductDetailView.as_view()), name='product_view'),
    path('edit/<int:pk>', ProductUpdateView.as_view(), name='product_edit'),
    path('delete/<int:pk>', ProductDeleteView.as_view(), name='product_delete'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
]

config/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blogpost')),
    path('users/', include('users.urls', namespace='user')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.views.generic import TemplateView

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, verify_email, EmailVerificationNoticeView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('confirm_email/<str:verification_code>/', verify_email, name='confirm_email'),
    path('warning_message/', EmailVerificationNoticeView.as_view(), name='notification'),

]

catalog/models.py
from datetime import date

from django.conf import settings
from django.db import models

NULLABLE = {'blank': True, 'null': True}

class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='название')
    description = models.CharField(max_length=200, verbose_name='описание')


    def __str__(self):
        return f'{self.name}'

class Product(models.Model):
    name = models.CharField(max_length=50, verbose_name='название')
    description = models.CharField(max_length=200, verbose_name='описание', **NULLABLE)
    image = models.ImageField(upload_to='product_image/', **NULLABLE, verbose_name='фото')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категория')
    price = models.PositiveIntegerField(verbose_name='цена')
    creation_date = models.DateField(default=date.today, verbose_name='дата создания', **NULLABLE)
    last_modification_date = models.DateField(default=date.today, verbose_name='дата редактирования', **NULLABLE)
    is_active = models.BooleanField(default=False)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE)

    def __str__(self):
        return f'{self.name}'

class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    version_number = models.CharField(max_length=20, verbose_name='номер версии')
    version_name = models.CharField(max_length=100, verbose_name='название версии')
    is_current_version = models.BooleanField(default=False, verbose_name='признак текущей версии')

    def __str__(self):
        return f'{self.version_name}'

catalog/forms.py
from django import forms

from catalog.models import Product, Version

class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Product
        fields = ('name', 'price', 'category')



    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        stop_list = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

        if cleaned_data in stop_list:
            raise forms.ValidationError('Запрещенный продукт')
        return cleaned_data


class VersionForm(forms.ModelForm):

    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.forms import ModelChoiceField, inlineformset_factory
from django.http import Http404
from django.shortcuts import render
from catalog.models import Product, Category, Version
from catalog.forms import ProductForm, VersionForm

from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from pytils.translit import slugify
from django.urls import reverse_lazy, reverse

from catalog.services import get_categories_cache


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context

    def form_valid(self, form):
        product = form.save(commit=False)
        product.creator = self.request.user
        product.save()
        return super().form_valid(form)

class ProductListView(ListView):
    model = Product

class ProductDetailView(DetailView):
    model = Product

class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:product_list')

class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)

        # Проверяем, является ли текущий пользователь создателем или модератором
        user_is_creator_or_moderator = (
                self.request.user == self.object.creator or
                self.request.user.is_staff  # Проверка на модератора (is_staff)
        )

        if not user_is_creator_or_moderator:
            raise Http404

        return self.object

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['categories'] = Category.objects.all()

        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        with transaction.atomic():
            self.object = form.save()
            if formset.is_valid():
                formset.instance = self.object
                formset.save()

        return super().form_valid(form)

class CategoryListView(ListView):
    model = Category

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['category_list'] = get_categories_cache()
        return context_data

# def contacts(request):
#     if request.method == 'POST':
#         # в переменной request хранится информация о методе, который отправлял пользователь
#         name = request.POST.get('name')
#         email = request.POST.get('phone')
#         message = request.POST.get('message')
#         # а также передается информация, которую заполнил пользователь
#         print(f"{name} - {email} - {message}")
#     return render(request, 'Product/contacts.html')

catalog/templates/catalog/includes/sidebar.html
    <div class="sidebar d-flex flex-column align-items-start justify-content-between">
        <a href="/" class="d-flex align-items-center mb-3 text-white text-decoration-none">
            <svg class="bi pe-none me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
            <span class="fs-4">Меню</span>
        </a>
        <hr>
        <ul class="nav nav-pills flex-column mb-auto">
            <li class="nav-item">
                <a href="/" class="nav-link active" aria-current="page">
                    <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
                    Главная
                </a>
            </li>
            <li>
                <a href="/contacts" class="nav-link text-white">
                    <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#speedometer2"></use></svg>
                    Категории
                </a>
            </li>
            <li>
                <a href="#" class="nav-link text-white">
                    <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#table"></use></svg>
                    Заказы
                </a>
            </li>
            <li>
                <a href="/contacts" class="nav-link text-white">
                    <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#grid"></use></svg>
                    Контакты
                </a>
            </li>
            <li>
                <a href="/blog" class="nav-link text-white">
                    <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#grid"></use></svg>
                    Блог
                </a>
            </li>
        </ul>
        <hr>
        <div class="dropdown">
            <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle"
               data-bs-toggle="dropdown" aria-expanded="false">
                <img src="
                {% if user.avatar %}
                    {{ user.avatar.url }}
                    {% else %}

                    {% endif %}
                         " alt="" width="32" height="32" class="rounded-circle me-2">
                <strong>
                    {% if user.is_authenticated %}
                    {{ user.first_name }}
                    {% else %}
                    Пользователь
                    {% endif %}

                </strong>
            </a>
            <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
                {% if user.is_authenticated %}
                <li><a class="dropdown-item" href="{% url 'user:logout' %}">Выйти</a></li>
                <li><a class="dropdown-item" href="{% url 'user:profile' %}">Редактировать профиль</a></li>
                {% else %}
                <li><a class="dropdown-item" href="{% url 'user:login' %}">Войти</a></li>
                <li><a class="dropdown-item" href="{% url 'user:register' %}">Регистрация</a></li>
                {% endif %}
            </ul>
        </div>
    </div>