blog/urls.py
from django.urls import path
from blog.views import BlogCreateView, BlogDeleteView, BlogListView, BlogDetailView, BlogUpdateView
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('', BlogListView.as_view(), name='blog_list'),
    path('view/<slug:slug>', BlogDetailView.as_view(), name='blog_view'),
    path('edit/<slug:slug>', BlogUpdateView.as_view(), name='blog_edit'),
    path('delete/<slug:slug>', BlogDeleteView.as_view(), name='blog_delete'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import ProductListView, ProductCreateView, ProductDetailView, ProductDeleteView, ProductUpdateView, \
    CategoryListView

app_name = CatalogConfig.name

urlpatterns = [
    # path('contacts/', contacts),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('', ProductListView.as_view(), name='product_list'),
    path('view/<int:pk>', cache_page(60)(ProductDetailView.as_view()), name='product_view'),
    path('edit/<int:pk>', ProductUpdateView.as_view(), name='product_edit'),
    path('delete/<int:pk>', ProductDeleteView.as_view(), name='product_delete'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
]

config/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blogpost')),
    path('users/', include('users.urls', namespace='user')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from datetime import date

from django.conf import settings
from django.db import models

NULLABLE = {'blank': True, 'null': True}

class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='название')
    description = models.CharField(max_length=200, verbose_name='описание')


    def __str__(self):
        return f'{self.name}'

class Product(models.Model):
    name = models.CharField(max_length=50, verbose_name='название')
    description = models.CharField(max_length=200, verbose_name='описание', **NULLABLE)
    image = models.ImageField(upload_to='product_image/', **NULLABLE, verbose_name='фото')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категория')
    price = models.PositiveIntegerField(verbose_name='цена')
    creation_date = models.DateField(default=date.today, verbose_name='дата создания', **NULLABLE)
    last_modification_date = models.DateField(default=date.today, verbose_name='дата редактирования', **NULLABLE)
    is_active = models.BooleanField(default=False)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE)

    def __str__(self):
        return f'{self.name}'

class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    version_number = models.CharField(max_length=20, verbose_name='номер версии')
    version_name = models.CharField(max_length=100, verbose_name='название версии')
    is_current_version = models.BooleanField(default=False, verbose_name='признак текущей версии')

    def __str__(self):
        return f'{self.version_name}'

catalog/forms.py
from django import forms

from catalog.models import Product, Version

class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Product
        fields = ('name', 'price', 'category')



    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        stop_list = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

        if cleaned_data in stop_list:
            raise forms.ValidationError('Запрещенный продукт')
        return cleaned_data


class VersionForm(forms.ModelForm):

    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.forms import ModelChoiceField, inlineformset_factory
from django.http import Http404
from django.shortcuts import render
from catalog.models import Product, Category, Version
from catalog.forms import ProductForm, VersionForm

from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from pytils.translit import slugify
from django.urls import reverse_lazy, reverse

from catalog.services import get_categories_cache


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context

    def form_valid(self, form):
        product = form.save(commit=False)
        product.creator = self.request.user
        product.save()
        return super().form_valid(form)

class ProductListView(ListView):
    model = Product

class ProductDetailView(DetailView):
    model = Product

class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:product_list')

class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)

        # Проверяем, является ли текущий пользователь создателем или модератором
        user_is_creator_or_moderator = (
                self.request.user == self.object.creator or
                self.request.user.is_staff  # Проверка на модератора (is_staff)
        )

        if not user_is_creator_or_moderator:
            raise Http404

        return self.object

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['categories'] = Category.objects.all()

        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        with transaction.atomic():
            self.object = form.save()
            if formset.is_valid():
                formset.instance = self.object
                formset.save()

        return super().form_valid(form)

class CategoryListView(ListView):
    model = Category

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['category_list'] = get_categories_cache()
        return context_data

# def contacts(request):
#     if request.method == 'POST':
#         # в переменной request хранится информация о методе, который отправлял пользователь
#         name = request.POST.get('name')
#         email = request.POST.get('phone')
#         message = request.POST.get('message')
#         # а также передается информация, которую заполнил пользователь
#         print(f"{name} - {email} - {message}")
#     return render(request, 'Product/contacts.html')

catalog/templates/catalog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}My Website{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
          crossorigin="anonymous">
</head>
<style>
     /* Дополнительные стили */
     body {
         background-color: #f8f9fa;
         font-family: Arial, sans-serif;
     }
    .sidebar {
         height: 100vh;
         background-color: #343a40;
         color: white;
         padding: 20px;
     }
    .content {
         margin-top: 20px;
     }

     .card-img-top {
         width: 100%;
         height: 200px;
         object-fit: cover;
     }

     .card-title {
         margin-bottom: 10px;
     }

     .card-text {
         height: 60px;
         overflow: hidden;
     }
 </style>
<body>
<div class="d-flex flex-row">
    <!-- Sidebar -->
    {% include 'catalog/includes/sidebar.html' %}

    <!-- Контент с карточками -->
    <div class="content container">
        {% block content %}{% endblock %}
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"
        integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS"
        crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}
{% load tags %}

{% block title %}Категории{% endblock %}

{% block content %}
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
        {% for object in object_list %}
        <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-body">
                    <h5 class="card-title">{{ object.name }}</h5>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block title %}Contacts{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <input type="text" name="name" />
        <input type="email" name="email" />
        <input type="submit" value="Отправить" />
    </form>
{% endblock %}

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}
{% load tags %}

{% block title %}На главной странице{% endblock %}

{% block content %}
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
        <h1 class="display-4 fw-normal text-body-emphasis">На главной странице</h1>
        <p class="fs-5 text-body-secondary">Вы находитесь на сайте продаж</p>
    </div>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
        {% for object in object_list %}
        <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
                <img src="{{ object.image|media_path }}" class="card-img-top" alt="Изображение товара">
                <div class="card-body">
                    <h4 class="card-title">{{ object }}</h4>
                    <h1 class="card-title pricing-card-title">{{ object.price }}$<small
                            class="text-body-secondary fw-light"></small></h1>
                    <p class="card-text">{{ object.description | truncatewords:100 }}</p>
                    <li class="nav-item">
                        <a href="/detail/{{ object.id }}" class="nav-link active" aria-current="page">
                            <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
                            Купить
                        </a>
                    </li>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container">
    <h1 class="display-4">Confirm Delete</h1>
    <p>Are you sure you want to delete the blog post with title: <strong>{{ object.name }}</strong>?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="/" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock content %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container">
    <h1 class="display-4">{{ object.name }}</h1>
    <p class="lead">{{ object.description }}</p>
    <p class="h3">Дата создания: {{ object.creation_date }}</p>
    <p class="h3">Количество просмотров: {{ object.price }}</p>
</div>
{% endblock content %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    <div class="card_body">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">
            {% if object%}
            Save
        {% else %}
            Create
        {% endif %}
    </button>
    </div>
    <div class="card_body">
        {{ formset.management_form }}
        {% for form in formset.forms %}
        {{ form.as_p }}
        {% endfor %}
    </div>


</form>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load tags %}

{% block title %}На главной странице{% endblock %}

{% block content %}
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
        <h1 class="display-4 fw-normal text-body-emphasis">На главной странице</h1>
        <p class="fs-5 text-body-secondary">Вы находитесь на сайте продаж</p>
    </div>
    <div class="row">
        <div class="col-md-12 mb-3">
            {% if user.is_authenticated %}
            <a href="{% url 'catalog:create' %}" class="btn btn-primary float-right">Добавить</a>
            {% endif %}
        </div>
    </div>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
        {% for object in object_list %}
        {% if object.is_active %}
        <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
                <img src="{{ object.image|media_path }}" class="card-img-top" alt="Изображение товара">
                <div class="card-body">
                    <h5 class="card-title">{{ object.name }}</h5>
                    <p class="card-text">{{ object.price}}</p>
                    <a href="{% url 'catalog:product_view' object.pk %}" class="btn btn-primary">View</a>
                    {% if user.is_authenticated and user == object.creator %}
                    <a href="{% url 'catalog:product_edit' object.pk %}" class="btn btn-secondary">Edit</a>
                    <a href="{% url 'catalog:product_delete' object.pk %}" class="btn btn-danger">Delete</a>
                    {% endif %}



                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
{% endblock %}